-- RS Group Medical Shop Management System — PostgreSQL / Supabase schema
-- Everything lives in a dedicated "rsgroup" schema so it never collides with
-- other apps sharing the same Supabase project (public schema is untouched).

CREATE SCHEMA IF NOT EXISTS rsgroup;
SET search_path TO rsgroup;

CREATE TABLE IF NOT EXISTS branches (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  address TEXT DEFAULT '',
  city TEXT DEFAULT '',
  phone TEXT DEFAULT '',
  email TEXT DEFAULT '',
  gstin TEXT DEFAULT '',
  drug_license TEXT DEFAULT '',
  active INTEGER DEFAULT 1,
  created_at TIMESTAMP(0) DEFAULT now()
);

CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  phone TEXT DEFAULT '',
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('super_admin','branch_admin','branch_manager','billing_staff','inventory_staff','accountant','delivery_staff','auditor')),
  branch_id INTEGER REFERENCES branches(id),
  extra_permissions TEXT DEFAULT '[]',
  denied_permissions TEXT DEFAULT '[]',
  active INTEGER DEFAULT 1,
  reset_token TEXT,
  reset_token_expires TEXT,
  created_at TIMESTAMP(0) DEFAULT now()
);

CREATE TABLE IF NOT EXISTS permissions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role TEXT NOT NULL,
  permission TEXT NOT NULL,
  UNIQUE(role, permission)
);

CREATE TABLE IF NOT EXISTS login_history (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER REFERENCES users(id),
  email TEXT,
  ip TEXT,
  user_agent TEXT,
  device TEXT,
  success INTEGER DEFAULT 1,
  created_at TIMESTAMP(0) DEFAULT now()
);

CREATE TABLE IF NOT EXISTS sessions (
  id TEXT PRIMARY KEY,
  user_id INTEGER REFERENCES users(id),
  ip TEXT,
  user_agent TEXT,
  device TEXT,
  created_at TIMESTAMP(0) DEFAULT now(),
  last_seen TIMESTAMP(0) DEFAULT now(),
  revoked INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS medicines (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  generic_name TEXT DEFAULT '',
  category TEXT DEFAULT 'General',
  brand TEXT DEFAULT '',
  barcode TEXT,
  hsn TEXT DEFAULT '3004',
  gst_rate DOUBLE PRECISION DEFAULT 12,
  unit TEXT DEFAULT 'Strip',
  rack_location TEXT DEFAULT '',
  min_stock INTEGER DEFAULT 10,
  prescription_required INTEGER DEFAULT 0,
  active INTEGER DEFAULT 1,
  created_at TIMESTAMP(0) DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_medicines_name ON medicines(name);
CREATE INDEX IF NOT EXISTS idx_medicines_barcode ON medicines(barcode);

CREATE TABLE IF NOT EXISTS suppliers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  contact_person TEXT DEFAULT '',
  phone TEXT DEFAULT '',
  email TEXT DEFAULT '',
  address TEXT DEFAULT '',
  gstin TEXT DEFAULT '',
  drug_license TEXT DEFAULT '',
  opening_balance DOUBLE PRECISION DEFAULT 0,
  active INTEGER DEFAULT 1,
  created_at TIMESTAMP(0) DEFAULT now()
);

CREATE TABLE IF NOT EXISTS stock_batches (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  medicine_id INTEGER NOT NULL REFERENCES medicines(id),
  branch_id INTEGER NOT NULL REFERENCES branches(id),
  supplier_id INTEGER REFERENCES suppliers(id),
  batch_no TEXT NOT NULL,
  expiry_date DATE NOT NULL,
  mrp DOUBLE PRECISION NOT NULL,
  purchase_price DOUBLE PRECISION NOT NULL,
  selling_price DOUBLE PRECISION NOT NULL,
  qty INTEGER NOT NULL DEFAULT 0,
  damaged_qty INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP(0) DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_batches_med_branch ON stock_batches(medicine_id, branch_id);
CREATE INDEX IF NOT EXISTS idx_batches_expiry ON stock_batches(expiry_date);

CREATE TABLE IF NOT EXISTS purchases (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  branch_id INTEGER NOT NULL REFERENCES branches(id),
  supplier_id INTEGER NOT NULL REFERENCES suppliers(id),
  invoice_no TEXT NOT NULL,
  invoice_date DATE NOT NULL,
  subtotal DOUBLE PRECISION DEFAULT 0,
  gst_amount DOUBLE PRECISION DEFAULT 0,
  total DOUBLE PRECISION DEFAULT 0,
  paid_amount DOUBLE PRECISION DEFAULT 0,
  status TEXT DEFAULT 'received' CHECK (status IN ('pending','received','returned')),
  invoice_file TEXT,
  notes TEXT DEFAULT '',
  created_by INTEGER REFERENCES users(id),
  created_at TIMESTAMP(0) DEFAULT now()
);

CREATE TABLE IF NOT EXISTS purchase_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  purchase_id INTEGER NOT NULL REFERENCES purchases(id) ON DELETE CASCADE,
  medicine_id INTEGER NOT NULL REFERENCES medicines(id),
  batch_id INTEGER REFERENCES stock_batches(id),
  batch_no TEXT NOT NULL,
  expiry_date DATE NOT NULL,
  qty INTEGER NOT NULL,
  free_qty INTEGER DEFAULT 0,
  purchase_price DOUBLE PRECISION NOT NULL,
  mrp DOUBLE PRECISION NOT NULL,
  selling_price DOUBLE PRECISION NOT NULL,
  gst_rate DOUBLE PRECISION DEFAULT 12,
  amount DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS purchase_returns (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  purchase_id INTEGER REFERENCES purchases(id),
  branch_id INTEGER NOT NULL REFERENCES branches(id),
  supplier_id INTEGER NOT NULL REFERENCES suppliers(id),
  reason TEXT DEFAULT '',
  amount DOUBLE PRECISION DEFAULT 0,
  created_by INTEGER REFERENCES users(id),
  created_at TIMESTAMP(0) DEFAULT now()
);

CREATE TABLE IF NOT EXISTS purchase_return_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  return_id INTEGER NOT NULL REFERENCES purchase_returns(id) ON DELETE CASCADE,
  medicine_id INTEGER NOT NULL REFERENCES medicines(id),
  batch_id INTEGER REFERENCES stock_batches(id),
  qty INTEGER NOT NULL,
  amount DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS supplier_payments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  supplier_id INTEGER NOT NULL REFERENCES suppliers(id),
  branch_id INTEGER REFERENCES branches(id),
  purchase_id INTEGER REFERENCES purchases(id),
  amount DOUBLE PRECISION NOT NULL,
  method TEXT DEFAULT 'cash',
  ref_no TEXT DEFAULT '',
  date DATE NOT NULL,
  notes TEXT DEFAULT '',
  created_by INTEGER REFERENCES users(id),
  created_at TIMESTAMP(0) DEFAULT now()
);

CREATE TABLE IF NOT EXISTS customers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  branch_id INTEGER REFERENCES branches(id),
  name TEXT NOT NULL,
  phone TEXT NOT NULL,
  email TEXT DEFAULT '',
  address TEXT DEFAULT '',
  dob DATE,
  loyalty_points DOUBLE PRECISION DEFAULT 0,
  credit_limit DOUBLE PRECISION DEFAULT 0,
  notes TEXT DEFAULT '',
  active INTEGER DEFAULT 1,
  created_at TIMESTAMP(0) DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_customers_phone ON customers(phone);

CREATE TABLE IF NOT EXISTS sales (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_no TEXT UNIQUE NOT NULL,
  branch_id INTEGER NOT NULL REFERENCES branches(id),
  customer_id INTEGER REFERENCES customers(id),
  staff_id INTEGER REFERENCES users(id),
  subtotal DOUBLE PRECISION DEFAULT 0,
  discount DOUBLE PRECISION DEFAULT 0,
  gst_amount DOUBLE PRECISION DEFAULT 0,
  round_off DOUBLE PRECISION DEFAULT 0,
  total DOUBLE PRECISION DEFAULT 0,
  paid_cash DOUBLE PRECISION DEFAULT 0,
  paid_upi DOUBLE PRECISION DEFAULT 0,
  paid_card DOUBLE PRECISION DEFAULT 0,
  credit_amount DOUBLE PRECISION DEFAULT 0,
  status TEXT DEFAULT 'completed' CHECK (status IN ('completed','held','cancelled','returned','partial_return')),
  doctor_name TEXT DEFAULT '',
  prescription_file TEXT,
  delivery_status TEXT,
  delivery_staff_id INTEGER REFERENCES users(id),
  delivery_address TEXT,
  delivered_at TIMESTAMP(0),
  notes TEXT DEFAULT '',
  created_at TIMESTAMP(0) DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_sales_branch_date ON sales(branch_id, created_at);
CREATE INDEX IF NOT EXISTS idx_sales_customer ON sales(customer_id);

CREATE TABLE IF NOT EXISTS sale_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sale_id INTEGER NOT NULL REFERENCES sales(id) ON DELETE CASCADE,
  medicine_id INTEGER NOT NULL REFERENCES medicines(id),
  batch_id INTEGER REFERENCES stock_batches(id),
  batch_no TEXT DEFAULT '',
  qty INTEGER NOT NULL,
  returned_qty INTEGER DEFAULT 0,
  mrp DOUBLE PRECISION NOT NULL,
  price DOUBLE PRECISION NOT NULL,
  purchase_price DOUBLE PRECISION DEFAULT 0,
  gst_rate DOUBLE PRECISION DEFAULT 12,
  gst_amount DOUBLE PRECISION DEFAULT 0,
  discount DOUBLE PRECISION DEFAULT 0,
  total DOUBLE PRECISION NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_sale_items_sale ON sale_items(sale_id);

CREATE TABLE IF NOT EXISTS returns (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sale_id INTEGER NOT NULL REFERENCES sales(id),
  branch_id INTEGER NOT NULL REFERENCES branches(id),
  customer_id INTEGER REFERENCES customers(id),
  staff_id INTEGER REFERENCES users(id),
  reason TEXT DEFAULT '',
  refund_amount DOUBLE PRECISION DEFAULT 0,
  refund_method TEXT DEFAULT 'cash',
  created_at TIMESTAMP(0) DEFAULT now()
);

CREATE TABLE IF NOT EXISTS return_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  return_id INTEGER NOT NULL REFERENCES returns(id) ON DELETE CASCADE,
  sale_item_id INTEGER NOT NULL REFERENCES sale_items(id),
  medicine_id INTEGER NOT NULL REFERENCES medicines(id),
  batch_id INTEGER REFERENCES stock_batches(id),
  qty INTEGER NOT NULL,
  amount DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS payments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  branch_id INTEGER REFERENCES branches(id),
  customer_id INTEGER REFERENCES customers(id),
  sale_id INTEGER REFERENCES sales(id),
  amount DOUBLE PRECISION NOT NULL,
  method TEXT DEFAULT 'cash',
  type TEXT DEFAULT 'receipt' CHECK (type IN ('receipt','refund')),
  ref_no TEXT DEFAULT '',
  date DATE NOT NULL,
  notes TEXT DEFAULT '',
  created_by INTEGER REFERENCES users(id),
  created_at TIMESTAMP(0) DEFAULT now()
);

CREATE TABLE IF NOT EXISTS expenses (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  branch_id INTEGER NOT NULL REFERENCES branches(id),
  category TEXT NOT NULL,
  amount DOUBLE PRECISION NOT NULL,
  date DATE NOT NULL,
  paid_method TEXT DEFAULT 'cash',
  notes TEXT DEFAULT '',
  created_by INTEGER REFERENCES users(id),
  created_at TIMESTAMP(0) DEFAULT now()
);

CREATE TABLE IF NOT EXISTS cash_closings (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  branch_id INTEGER NOT NULL REFERENCES branches(id),
  date DATE NOT NULL,
  opening_balance DOUBLE PRECISION DEFAULT 0,
  cash_sales DOUBLE PRECISION DEFAULT 0,
  cash_expenses DOUBLE PRECISION DEFAULT 0,
  cash_deposited DOUBLE PRECISION DEFAULT 0,
  expected_cash DOUBLE PRECISION DEFAULT 0,
  actual_cash DOUBLE PRECISION DEFAULT 0,
  difference DOUBLE PRECISION DEFAULT 0,
  notes TEXT DEFAULT '',
  closed_by INTEGER REFERENCES users(id),
  created_at TIMESTAMP(0) DEFAULT now(),
  UNIQUE(branch_id, date)
);

CREATE TABLE IF NOT EXISTS stock_transfers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  from_branch_id INTEGER NOT NULL REFERENCES branches(id),
  to_branch_id INTEGER NOT NULL REFERENCES branches(id),
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending','completed','cancelled')),
  notes TEXT DEFAULT '',
  created_by INTEGER REFERENCES users(id),
  completed_by INTEGER REFERENCES users(id),
  created_at TIMESTAMP(0) DEFAULT now(),
  completed_at TIMESTAMP(0)
);

CREATE TABLE IF NOT EXISTS stock_transfer_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  transfer_id INTEGER NOT NULL REFERENCES stock_transfers(id) ON DELETE CASCADE,
  medicine_id INTEGER NOT NULL REFERENCES medicines(id),
  batch_id INTEGER NOT NULL REFERENCES stock_batches(id),
  qty INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS stock_adjustments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  branch_id INTEGER NOT NULL REFERENCES branches(id),
  medicine_id INTEGER NOT NULL REFERENCES medicines(id),
  batch_id INTEGER NOT NULL REFERENCES stock_batches(id),
  qty_change INTEGER NOT NULL,
  type TEXT DEFAULT 'adjustment' CHECK (type IN ('adjustment','damage','expiry_writeoff')),
  reason TEXT NOT NULL,
  created_by INTEGER REFERENCES users(id),
  created_at TIMESTAMP(0) DEFAULT now()
);

CREATE TABLE IF NOT EXISTS staff_attendance (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id),
  branch_id INTEGER REFERENCES branches(id),
  date DATE NOT NULL,
  check_in TEXT,
  check_out TEXT,
  method TEXT DEFAULT 'mobile',
  notes TEXT DEFAULT '',
  UNIQUE(user_id, date)
);

CREATE TABLE IF NOT EXISTS tasks (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  branch_id INTEGER REFERENCES branches(id),
  assigned_to INTEGER REFERENCES users(id),
  title TEXT NOT NULL,
  description TEXT DEFAULT '',
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending','in_progress','done','cancelled')),
  due_date DATE,
  created_by INTEGER REFERENCES users(id),
  created_at TIMESTAMP(0) DEFAULT now(),
  completed_at TIMESTAMP(0)
);

CREATE TABLE IF NOT EXISTS notifications (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  branch_id INTEGER REFERENCES branches(id),
  user_id INTEGER REFERENCES users(id),
  role TEXT,
  type TEXT DEFAULT 'info',
  title TEXT NOT NULL,
  message TEXT DEFAULT '',
  read INTEGER DEFAULT 0,
  created_at TIMESTAMP(0) DEFAULT now()
);

CREATE TABLE IF NOT EXISTS audit_logs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER REFERENCES users(id),
  branch_id INTEGER REFERENCES branches(id),
  action TEXT NOT NULL,
  entity TEXT DEFAULT '',
  entity_id INTEGER,
  details TEXT DEFAULT '',
  ip TEXT DEFAULT '',
  created_at TIMESTAMP(0) DEFAULT now()
);

CREATE TABLE IF NOT EXISTS settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

-- The app connects with the postgres role (table owner) and bypasses RLS.
-- Enabling RLS with no policies blocks all access through Supabase's
-- auto-generated REST API (anon/authenticated roles) — deny by default.
DO $$
DECLARE t text;
BEGIN
  FOR t IN SELECT tablename FROM pg_tables WHERE schemaname = 'rsgroup'
  LOOP
    EXECUTE format('ALTER TABLE rsgroup.%I ENABLE ROW LEVEL SECURITY', t);
  END LOOP;
END $$;

-- v2: multi-branch users, pharmacist role, customer GST/type, branch manager,
-- supplier payment terms (idempotent — safe to run on every boot)
ALTER TABLE users ADD COLUMN IF NOT EXISTS extra_branches TEXT DEFAULT '[]';
ALTER TABLE users DROP CONSTRAINT IF EXISTS users_role_check;
ALTER TABLE users ADD CONSTRAINT users_role_check CHECK (role IN
  ('super_admin','branch_admin','branch_manager','pharmacist','billing_staff','inventory_staff','accountant','delivery_staff','auditor'));
ALTER TABLE customers ADD COLUMN IF NOT EXISTS gstin TEXT DEFAULT '';
ALTER TABLE customers ADD COLUMN IF NOT EXISTS customer_type TEXT DEFAULT 'individual';
ALTER TABLE branches ADD COLUMN IF NOT EXISTS manager TEXT DEFAULT '';
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS payment_terms TEXT DEFAULT '';

-- v3: discount management (promotions, customer/user discount config, bill
-- discount details) + stock update notifications (idempotent)
CREATE TABLE IF NOT EXISTS promotions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT DEFAULT '',
  branch_id INTEGER REFERENCES branches(id),
  discount_type TEXT NOT NULL DEFAULT 'percent' CHECK (discount_type IN ('percent','amount')),
  discount_value DOUBLE PRECISION NOT NULL DEFAULT 0,
  applies_to TEXT NOT NULL DEFAULT 'all' CHECK (applies_to IN ('all','category','medicine')),
  category TEXT DEFAULT '',
  medicine_id INTEGER REFERENCES medicines(id),
  min_bill_amount DOUBLE PRECISION DEFAULT 0,
  from_date DATE NOT NULL,
  to_date DATE NOT NULL,
  active INTEGER DEFAULT 1,
  created_by INTEGER REFERENCES users(id),
  created_at TIMESTAMP(0) DEFAULT now()
);
ALTER TABLE rsgroup.promotions ENABLE ROW LEVEL SECURITY;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS discount_percent DOUBLE PRECISION DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS max_discount_percent DOUBLE PRECISION;
ALTER TABLE sales ADD COLUMN IF NOT EXISTS discount_type TEXT DEFAULT 'none';
ALTER TABLE sales ADD COLUMN IF NOT EXISTS discount_value DOUBLE PRECISION DEFAULT 0;
ALTER TABLE sales ADD COLUMN IF NOT EXISTS item_discount DOUBLE PRECISION DEFAULT 0;
ALTER TABLE sales ADD COLUMN IF NOT EXISTS promo_id INTEGER REFERENCES promotions(id);
ALTER TABLE sales ADD COLUMN IF NOT EXISTS discount_approved_by INTEGER REFERENCES users(id);
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS data TEXT;

-- v4: strip count on medicines (tablets/capsules per strip)
ALTER TABLE medicines ADD COLUMN IF NOT EXISTS strip_count INTEGER DEFAULT 1;
