-- v3: discount management (promotions, customer/user discount config, bill
-- discount details) + stock update notifications
SET search_path TO rsgroup;

CREATE TABLE IF NOT EXISTS promotions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT DEFAULT '',
  branch_id INTEGER REFERENCES branches(id),
  discount_type TEXT NOT NULL DEFAULT 'percent' CHECK (discount_type IN ('percent','amount')),
  discount_value DOUBLE PRECISION NOT NULL DEFAULT 0,
  applies_to TEXT NOT NULL DEFAULT 'all' CHECK (applies_to IN ('all','category','medicine')),
  category TEXT DEFAULT '',
  medicine_id INTEGER REFERENCES medicines(id),
  min_bill_amount DOUBLE PRECISION DEFAULT 0,
  from_date DATE NOT NULL,
  to_date DATE NOT NULL,
  active INTEGER DEFAULT 1,
  created_by INTEGER REFERENCES users(id),
  created_at TIMESTAMP(0) DEFAULT now()
);
ALTER TABLE rsgroup.promotions ENABLE ROW LEVEL SECURITY;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS discount_percent DOUBLE PRECISION DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS max_discount_percent DOUBLE PRECISION;
ALTER TABLE sales ADD COLUMN IF NOT EXISTS discount_type TEXT DEFAULT 'none';
ALTER TABLE sales ADD COLUMN IF NOT EXISTS discount_value DOUBLE PRECISION DEFAULT 0;
ALTER TABLE sales ADD COLUMN IF NOT EXISTS item_discount DOUBLE PRECISION DEFAULT 0;
ALTER TABLE sales ADD COLUMN IF NOT EXISTS promo_id INTEGER REFERENCES promotions(id);
ALTER TABLE sales ADD COLUMN IF NOT EXISTS discount_approved_by INTEGER REFERENCES users(id);
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS data TEXT;
